### ISSUE TITLE
Feat: Copy Button

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Chirantanbanik/Random-Joke-Generator#11]
![copy btn feat](https://user-images.githubusercontent.com/68139593/193397449-b7bb19f1-6500-4eff-995b-42be585d819c.png)

**Comment by BismeetSingh** [comment]
I can do this, can you assign it

**Comment by BismeetSingh** [comment]
okay, its already done :)

**Comment by Aryan-Srivastava** [comment]
yeah I already did it just needed to push the changes, you can open your own issue, there are room for multiple improvements. Go ahead

**Comment by Aryan-Srivastava** [comment]
#39
