### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Farhan-Ali2002** [Chirantanbanik/Random-Joke-Generator#5]
I want to add a dark mode to this project! There will be an icon in top-right of the page which will switch the modes when clicked!
I have already completed it
![darkmode](https://user-images.githubusercontent.com/109536970/193393986-1b1e128e-8c80-409c-8023-f2f77cf28ead.PNG)
![lightmode](https://user-images.githubusercontent.com/109536970/193393988-6a10799b-9d52-41ae-85bc-5042e278a019.PNG)
! I want you to assign me this task so that i can make a pull request!
Thank You!
#hacktoberfest2022

**Comment by Chirantanbanik** [comment]
That's great Farhan, go for it👍🏼

**Comment by Farhan-Ali2002** [comment]
> That's great Farhan, go for it👍🏼

Thankyou :))

**Comment by Chirantanbanik** [comment]
Great work Farhan👏🏻
